### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by Hossman333** [Xaeroxe/nitro-game-engine#8]
Seems a lil chaotic.

**Comment by Xaeroxe** [comment]
I typically prefer to "write it down now and organize later".  I like this because the ideal organization won't be apparent until more code is present.  So I'll keep this issue open and close it after I've organized and refactored.

**Comment by Xaeroxe** [comment]
Some musings on good ways to accomplish this: ~~gnu-mingw and msvc are folders that contain libs and dlls but that's not apparent until you open them, we can make that more obvious at a surface level by switching the folder hierarchy to be more like this:~~
~~lib/gnu-mingw/32~~
~~dll/gnu-mingw/32~~

~~instead of its current form.~~ Edit: this has been completed.

~~Audio is also scattered throughout app.rs, so moving that into it's own structure that will become part of App would be a good idea, it would especially help with keeping relevant functionality in one place.~~ Edit: this has been completed.

pub(restricted) would help with organization a lot, as it would remove the need for these _private modules.  That feature is ready to be stabilized in https://github.com/rust-lang/rust ~~they're just waiting for someone to do it, so I think I'll submit a PR to stabilize that feature, then once it is released we can clean up this filesystem.~~ Edit: As I was just getting ready to start creating the PR I discovered @cramertj had already made the PR and it was well on its way into the repo.  Thanks cramer!

~~mod.rs files should be reserved for declaring other modules, this is not how I've been using them thus far though.~~ Edit: This has been completed.

**Comment by Xaeroxe** [comment]
https://github.com/rust-lang/rust/pull/40556 pub(restricted) stabilization PR.  As soon as this is merged and released to stable I can clean up the accession chains.

**Comment by Xaeroxe** [comment]
https://github.com/Xaeroxe/nitro-game-engine/commit/01c60bf6f520abeb16d4579359af298faedc1d3d and https://github.com/Xaeroxe/nitro-game-engine/commit/e2601892084bdabd7bdbe7247cda5f568b072e3a helped with this quite a bit.  Once pub(restricted) lands and that's integrated into nitro I'll close this issue.

**Comment by Xaeroxe** [comment]
https://github.com/Xaeroxe/nitro-game-engine/commit/7b89aced490a76ab8145a5eb053e75e95df9483a yet another rearrangment commit.

**Comment by Xaeroxe** [comment]
Woo pub(restricted) stabilization PR has been merged!  Now we just have to wait for Rust 1.18

**Comment by Xaeroxe** [comment]
Rust 1.18 has been released, and the code has been updated to use it.  Closing this issue now.

**Comment by Hossman333** [comment]
Boom! 🎉 💥
